version: "3"
services:
  rethinkdb:
    image: "rethinkdb"
    expose:
      - 28015
      - 8080
    ports:
      - 28015:28015
      - 8080:8080
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 4000
    ports:
      - "80:4000"
    depends_on:
      - rethinkdb
    environment:
      RETHINK_HOST: rethinkdb
      RETHINK_PORT: 28015
      RETHINK_DB: maincoin
    command: ["node", "."]

  frontend:
    build:
      context: ./frontend-remake
      dockerfile: Dockerfile
    image: maincoin/frontend:1
    depends_on:
      - backend
    expose:
      - 3000
    ports:
      - 80:3000
    environment:
      WS_HOST: http://46.4.95.174
      WS_PORT: 4000
      BACK_HOST: http://46.4.95.174
      BACK_POTR: 4000
    command: ["yarn", "start"]
